Random password generator and it's test
MarkelAlvarez/SALC pull request #19
Opened 2021-05-03 16:19 UTC by MarkelAlvarez

Closes #4

2021-05-03 16:23 UTC, MarkelAlvarez commented
Peta el sonar, como siempre. El test comprueba que existen dos caracteres especiales en la contraseña generada. 

Ref: [https://www.baeldung.com/java-generate-secure-password](https://www.baeldung.com/java-generate-secure-password)

P.D.: ¿Los test unitarios los está detectando y corriendo bien?

2021-05-04 02:49 UTC, Missionpage requested changes
> Peta el sonar, como siempre. El test comprueba que existen dos caracteres especiales en la contraseña generada.

Sería interesante comprobar que no se genera la misma contraseña en un número considerable de intentos. [Aquí](https://www.baeldung.com/junit-5-repeated-test) te dejo una ref. de cómo hacer tests de manera que estos se repitan *n* veces

### En la clase ```PasswordGeneratorIT```

Se me ocurre almacenar la contraseña como atributo de clase cada vez que llamas al método, luego comprobar que se genera con los *x* caracteres especiales, *x* letras minúsculas, *x* letras mayúsculas, *x* dígitos. 

Luego de eso, comprobar que la contraseña generada no es igual a la contraseña generada (y almacenada) previamente. 

> P.D.: ¿Los test unitarios los está detectando y corriendo bien?

No, para ello debes agregar al _pom.xml_, en la etiqueta: `<build>` lo siguiente:

[pom-build.zip](https://github.com/MarkelAlvarez/SALC/files/6418766/pom-build.zip)

En la CI, cuando salta el **Java CI / build**, puedes ver en la sección _Build with Maven_, la ejecución de Maven, y a la hora de pasar los tests, te indica cuál está corriendo. 

![345817ba49097e1a568e294d1dfdfff2](https://user-images.githubusercontent.com/26282994/116955556-325c1e80-ac93-11eb-9c07-56db0d4b64dc.png)


Fuera de esto, viendo que has usado la librería `org.passay`, y que en nuestro SRS hemos indicado que las contraseñas que pidan cambiar los usuarios, cumplan los mismos requisitos que al generarla aleatoriamente: 

![password-req](https://user-images.githubusercontent.com/26282994/116955060-cd53f900-ac91-11eb-8865-201d2a55b59e.png)

Creo que tendremos que agregar una nueva clase ```PasswordValidatorService``` que se encargue de validar las nuevas contraseñas. [Aquí](https://www.baeldung.com/java-passay) hay información más que necesaria sobre cómo implementarla - o eso creo.

#10 Queda pendiente actualizar la implementación de esta clase en el diagrama de clases. 
#10 Queda pendiente agregar la dependencia con ```org.passay```, y agregar la posible clase ```PasswordValidatorService``` en el diagrama de clases.

2021-05-04 02:49 UTC, LuisEgui commented on src/main/java/com/ahsoka/SALC/user_model/service/PasswdGenerator.java
> +public class PasswdGenerator {
Veo que has cambiado el nombre de la clase para resolver el conflicto con la clase ```org.passay.PasswordGenerator```, pero recomiendo que el nombre de la clase sea completo, por ejemplo, se me ocurre llamarla: ```PasswordGeneratorService```

2021-05-15 16:18 UTC, MarkelAlvarez commented
No estoy del todo seguro de  como cambiar los RegEx para solucionar lo del Sonar, échale un vistazo a ver como lo harías tu

2021-05-18 00:13 UTC, Missionpage commented
> No estoy del todo seguro de como cambiar los RegEx para solucionar lo del Sonar, échale un vistazo a ver como lo harías tu

1. He reducido el número de caracteres especiales a: `!@#$%^&*`.
2. He agrupado los caracteres permitidos para intentar evitar la vulnerabilidad (ReDoS)

El nuevo regex que propongo es:

```java 
public boolean passwordValidate (String password) {
    return password.matches("^(?=.{8,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.+[!@#$%^&*]).*$");
}
```

Preview del regex:

![regex](https://user-images.githubusercontent.com/26282994/118571224-d4910180-b77d-11eb-8bee-3f935201bcfb.png)

He hecho pruebas manuales de la expresión regular [aquí](regexr.com/5t4g6).

Algunas referencias utilizadas han sido:

- [https://www.regular-expressions.info/catastrophic.html/regexbuddy/regexbuddy/duplicatelines.html](https://www.regular-expressions.info/catastrophic.html/regexbuddy/regexbuddy/duplicatelines.html)
- [https://riptutorial.com/regex/example/18996/a-password-containing-at-least-1-uppercase--1-lowercase--1-digit--1-special-character-and-have-a-length-of-at-least-of-10](https://riptutorial.com/regex/example/18996/a-password-containing-at-least-1-uppercase--1-lowercase--1-digit--1-special-character-and-have-a-length-of-at-least-of-10)
- [https://sonarcloud.io/project/security_hotspots?id=MarkelAlvarez_SALC&pullRequest=19](https://sonarcloud.io/project/security_hotspots?id=MarkelAlvarez_SALC&pullRequest=19)

2021-05-18 00:50 UTC, Missionpage requested changes
Me acabo de dar cuenta que llamas al `PasswordValidatorService` para comprobar que la contraseña es correcta. La creación de contraseñas no debería depender del PasswordValidatorService, para ello, se utilizan los asserts en los test. 

El test para PasswordGeneratorService quedaría tal que:

```java 
class PasswordGeneratorServiceIT {
    private PasswordGeneratorService passGen;
    private static String prevPasswd = "";

    @BeforeEach
    void before() {
        passGen = new PasswordGeneratorService();
    }

    @RepeatedTest(10)
    void testPasswordGenerator() {
        String password = passGen.generate();

        Assertions.assertNotEquals(prevPassword, password);
        
        prevPasswd = password;
    }
```

2021-05-18 10:00 UTC, merged